spring.application.name=api

# Konfigurasi Database (Membaca Environment Variable Railway / Default Localhost)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/db_melati?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Konfigurasi JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# URL rahasia menuju panel admin (tanpa slash depan/belakang)
app.admin-path=kelola-x92fp

# Folder tempat menyimpan file yang diupload dari admin panel (foto/video)
app.upload-dir=uploads

# Batas ukuran file upload (foto/video)
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# Port Server Dinamis dari Railway (Default Localhost: 8080)
server.port=${PORT:8080}

# Eksekusi Otomatis File schema.sql saat App Dijalankan
spring.sql.init.mode=always